export const GRAPH_CONSTANTS = {
	MAX_NODE_SIZE: 100,
	MIN_LINK_WIDTH: 1,
	MAX_LINK_WIDTH: 10,
	INITIAL_CORRELATION_THRESHOLD: 0.2,
	INITIAL_MIN_MEASUREMENTS: 100,
	LOG_SCALE: {
		MIN: Math.log(0.02),
		MAX: Math.log(123456),
	},
	FORCE: {
		LINK_DISTANCE: 200,
		CHARGE_STRENGTH: -200,
		CENTER_STRENGTH: 1,
	},
	ANIMATION: {
		ZOOM_DURATION: 400,
		INITIAL_TIMEOUT: 500,
	},
} as const;